#pragma once
#include <vector>

#include <imgui.h>

#include "wrappers\ModuleWrapper.h"

/*
Displays a view of all Modules in the application's pipeline. For each module
provided, the window will display collapsible sections for each pipeline stage
where each module can be re-ordered and their parameters modified.
*/
class PipelineView
{
public:
  void showWindow(std::vector<ModuleWrapper>);
  // TODO this parameter will receive the wrappers from the application's
  // context. The wrappers will be generated by the "Add modules" window
  // and returned to the application context.

};

